#配置熔断的超时时间
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
#配置路由策略
define:
  route:
    prod: false
spring:
  cloud:
    gateway:
      routes:
        # auth
        - id: api-auth
          uri: lb://auth-service
          predicates:
          - Path=/api-auth/**
       # - Weight=auth1, 90
          filters:
          - SwaggerHeaderFilter
          - StripPrefix=1

        # project
        - id: api-project
          uri: lb://project-service
          predicates:
            - Path=/api-project/**
          # - Weight=auth1, 90
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1

        # user
        - id: api-user
          uri: lb://user-service
          predicates:
            - Path=/api-user/**
          # - Weight=auth1, 90
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1

        #settlement
        - id: api-settlement
          uri: lb://settlement-service
          predicates:
            - Path=/api-settlement/**
          # - Weight=auth1, 90
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1


        - id: api-report
          uri: lb://report-service
          predicates:
            - Path=/api-report/**
          # - Weight=auth1, 90
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1

        - id: api-file
          uri: lb://file-service
          predicates:
            - Path=/api-file/**
          # - Weight=auth1, 90
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1



      discovery:
        locator:
          enabled: false    # 开启基于服务名访问的路由策略


#配置匿名访问url
jwt:
  exclude:
    urlPatterns:
      - /api-user/user/login
      - .*api-docs.*
      - .*swagger.*
      - /api-user/package/.*
      - /api-file/file/.*



session:
  domain: survey-gateway